palette = "catppuccin_frappe"

format = """
$cmd_duration\
[╭](bold black) $username\
$os\
$directory\
$fill\
$git_branch\
$git_commit\
$aws\
$kubernetes
[╰](bold black) $character
"""

[os]
disabled = false

[username]
show_always = false
disabled = true

[aws]
symbol = "  "
disabled = false
format = '[ $symbol$profile ]($style)'

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[cmd_duration]
min_time=500
show_milliseconds=true
format="""[󱎫 $duration]($style)
"""

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"
truncation_length = 0
truncate_to_repo = false
style = 'bold rosewater'

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fill]
symbol = '─'

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
format = '[ $symbol $branch ]($style)'

[git_commit]
disabled = false
tag_disabled = false
format = '[  $hash$tag ]($style)'
tag_symbol = '  '

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
disabled = false
format = '[ $symbol$context( \($namespace\)) ]($style)'

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Macos = " "
Arch = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

