#!/bin/sh
set -e

SSO_START_URL=$(aws configure get sso_start_url || true)

if [ -z "$SSO_START_URL" ]; then
    echo >&2 "No AWS SSO profile is active"
    exit 1
fi

SSO_ACCOUNT_ID=$(aws configure get sso_account_id)
SSO_ROLE_NAME=$(aws configure get sso_role_name)
SSO_REGION=$(aws configure get sso_region)

JSON_FILE=$(rg -l "$SSO_START_URL" ~/.aws/sso/cache || true)
if [ -z "$JSON_FILE" ]; then
    echo >&2 "No session exists; run aws sso login"
    exit 1
fi

ACCESS_TOKEN="$(jq -r .accessToken <"$JSON_FILE")"
CREDS_JSON="$(aws sso get-role-credentials --account-id "$SSO_ACCOUNT_ID" --role-name "$SSO_ROLE_NAME" --access-token "$ACCESS_TOKEN" --region "$SSO_REGION")"

echo "export AWS_ACCESS_KEY_ID=\"$(echo "$CREDS_JSON" | jq -r .roleCredentials.accessKeyId)\""
echo "export AWS_SECRET_ACCESS_KEY=\"$(echo "$CREDS_JSON" | jq -r .roleCredentials.secretAccessKey)\""
echo "export AWS_SESSION_TOKEN=\"$(echo "$CREDS_JSON" | jq -r .roleCredentials.sessionToken)\""

echo >&2 "Created temp credentials."
